apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: $PROVIDER_CONFIG_NAME
spec:
  projectID: $PROVIDER_PROJECT_ID
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-creds
      key: creds
