---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: mgmt-vpc
  labels:
    provider: aws
    vpc: mgmt-vpc
spec:
  forProvider:
    cidrBlock: "10.0.0.0/16"
    enableDnsHostNames: true
    enableDnsSupport: true
    instanceTenancy: default
    region: us-east-2
    tags:
      -
        key: Name
        value: mgmt-vpc
      -
        key: Manager
        value: crossplane
  providerConfigRef:
    name: aws-huxdev
---
# EKS cluster Subnets specified must be in at least two different AZs
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: ng-subnet1
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2a
    cidrBlock: 10.0.0.0/24
    vpcIdRef:
      name: mgmt-vpc
    mapPublicIPOnLaunch: true
    tags:
      -
        key: Name
        value: ng-subnet1
      -
        key: Manager
        value: crossplane
  providerConfigRef:
    name: aws-huxdev

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: ng-subnet2
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2b
    cidrBlock: 10.0.1.0/24
    vpcIdRef:
      name: mgmt-vpc
    mapPublicIPOnLaunch: true
    tags:
      -
        key: Name
        value: ng-subnet2
      -
        key: Manager
        value: crossplane
  providerConfigRef:
    name: aws-huxdev
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: ng-internetgateway
spec:
  forProvider:
    region: us-east-2
    vpcIdRef:
      name: mgmt-vpc
  providerConfigRef:
    name: aws-huxdev
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: ng-routetable
spec:
  forProvider:
    region: us-east-2
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: ng-internetgateway
    associations:
      - subnetIdRef:
          name: ng-subnet1
      - subnetIdRef:
          name: ng-subnet2
    vpcIdRef:
      name: mgmt-vpc
  providerConfigRef:
    name: aws-huxdev
