---
# AWS provider that references the secrete credentials
# https://github.com/crossplane/provider-aws/blob/master/examples/providerconfig/secret.yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-huxdev
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
