---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: ng-eks-sg
spec:
  forProvider:
    region: us-east-2
    vpcIdRef:
      name: mgmt-vpc
    groupName: ng-eks-workers-sg
    description: "Cluster communication with worker nodes"
    # egress:
    #   - ipProtocol: All
    #     ipRanges:
    #       - cidrIp: 0.0.0.0/0
    # ingress:
    #   - ipProtocol: All
    #     fromPort: 443
    #     toPort: 443
    #     ipRanges:
    #       - cidrIp: 10.0.0.1/32
    tags:
      - key: Name
        value: ng-eks-workers-sg
      - key: Manager
        value: crossplane
      - key: COUNTRY
        value: US
      - key: ENVIRONMENT
        value: PRD
      - key: FUNCTION
        value: CON
      - key: PRIMARYCONTACT
        value: jyoder@deloitte.com
      - key: SECONDARYCONTACT
        value: paulphillips@deloitte.com
      - key: MEMBERFIRM
        value: US
      - key: BILLINGCONTACT
        value: mcristalli@deloitte.com
      - key: CSTYPE
        value: Internal
      - key: CSCLASS
        value: Confidential
      - key: CSQUAL
        value: XSP Magnetic Dev/QA Public
      - key: BILLINGCODE
        value: LPXC2627-M1-01-92-5003
      # - key: DEMO_MESSAGE
      #   value: WESHOULDUSETHIS
  providerConfigRef:
    name: aws-huxdev
